
package com.epam.lab.webservice.impl;

import com.epam.lab.webservice.LocationService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocationServiceImplService", targetNamespace = "http://impl.webservice.lab.epam.com/", wsdlLocation = "http://localhost:8080/locationservice/locations?wsdl")
public class LocationServiceImplService
    extends Service
{

    private final static URL LOCATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOCATIONSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.lab.epam.com/", "LocationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/locationservice/locations?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOCATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LocationServiceImplService() {
        super(__getWsdlLocation(), LOCATIONSERVICEIMPLSERVICE_QNAME);
    }

    public LocationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public LocationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONSERVICEIMPLSERVICE_QNAME);
    }

    public LocationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public LocationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocationService
     */
    @WebEndpoint(name = "LocationServiceImplPort")
    public LocationService getLocationServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.lab.epam.com/", "LocationServiceImplPort"), LocationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationService
     */
    @WebEndpoint(name = "LocationServiceImplPort")
    public LocationService getLocationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.lab.epam.com/", "LocationServiceImplPort"), LocationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOCATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOCATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
