
package com.epam.lab.webservice;

import com.epam.lab.domain.ObjectFactory;
import com.epam.lab.domain.PlaceType;
import com.epam.lab.wrapper.Response;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocationService", targetNamespace = "http://webservice.lab.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocationService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.epam.lab.webservice.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.lab.epam.com/LocationService/addPlaceRequest", output = "http://webservice.lab.epam.com/LocationService/addPlaceResponse")
    public Response addPlace(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
                PlaceType arg1,
        @WebParam(name = "arg2", partName = "arg2")
        double arg2,
        @WebParam(name = "arg3", partName = "arg3")
        double arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.epam.lab.webservice.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.lab.epam.com/LocationService/checkinRequest", output = "http://webservice.lab.epam.com/LocationService/checkinResponse")
    public Response checkin(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.lab.webservice.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.lab.epam.com/LocationService/findFriendsByPlaceRequest", output = "http://webservice.lab.epam.com/LocationService/findFriendsByPlaceResponse")
    public Response findFriendsByPlace(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.epam.lab.webservice.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.lab.epam.com/LocationService/findFriendsByCoordinatesRequest", output = "http://webservice.lab.epam.com/LocationService/findFriendsByCoordinatesResponse")
    public Response findFriendsByCoordinates(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.epam.lab.webservice.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.lab.epam.com/LocationService/findNearPlacesByDistanceRequest", output = "http://webservice.lab.epam.com/LocationService/findNearPlacesByDistanceResponse")
    public Response findNearPlacesByDistance(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1,
        @WebParam(name = "arg2", partName = "arg2")
        long arg2);

}
